[[news]]
date = "2026-09"
content = "我的第一作者论文“Sensorless Control of Doubly Fed Induction Generators with Grid Fault Ride-Through Capability”已被 IEEE Transactions on Energy Conversion 录用。🎉"

[[news]]
date = "2026-07"
content = "关于异构智能体联邦强化学习与能源枢纽调度的论文已被 IEEE Transactions on Smart Grid 录用。🎉"

[[news]]
date = "2025-12"
content = "完成一项发明专利技术转让，转让金额为 15 万元。"

[[news]]
date = "2025-11"
content = "获国家奖学金。"

[[news]]
date = "2025-10"
content = "获香港大学电气工程博士录取。"

[[news]]
date = "2025-10"
content = "发明专利“无位置传感器双馈风力发电机控制方法及系统”正式授权。"

[[news]]
date = "2025-06"
content = "入选浙江大学“未来学术之星”计划并获 2 万元科研资助。"

[[news]]
date = "2025-05"
content = "获国家级大学生创新创业训练计划重点项目 2.4 万元资助。"
